### ISSUE TITLE
Aggregates and entities should not depend on the infrastructure

### ISSUE THREAD

**Issue by pith** [seedstack/business#1]
Currently, we provide JPA abstract classes for aggregates and entities. When these classes are extended this create a direct binding between the domain and the infrastructure. This doesn't respect the DDD principles and should be avoided.

A workaround could be to use interfaces for aggregates and entities and place implementations in the infrastructure layer. The problem with this solution is that when you will want to share your domain, you won't be able to share the business logic implementation.

So we will deprecate these classes and recommend to use JPA with an orm.xml file to do the JPA binding.

**Comment by pith** [comment]
@ejemba is this ok for you ?

**Comment by adrienlauer** [comment]
We may not especially recommend to use orm.xml files all the time. Only if we want to avoid a JPA dependency in a reusable domain or need that domain to be used in multiple applications with different relational persistence models. 

JPA annotations are meta to the code, so using them even in reusable domains is acceptable (but it limits implementation to one predefined relational model). This class can still be compatible with other persistence mechanisms.

By removing the JPA abstract classes, developers will be able to provide behavior-rich domain entities and VO (with more than just getters and setters) that can be reused in any persistence mechanism, JPA annotations or not.

**Comment by ejemba** [comment]
We also provide "blank" Domain Abstract Base so the project is not tied with JPA, if I remember well. 

As @adrienlauer said JPA annotation used in seed jpa business are just specs. So in a non JEE Server (or disabling jpa) it should be safe. I'm afraid moving stuff back to xml can afraid developers.

Any persistence mechanism will bring it's infrastructure. With another technology it'll have to be somewhere as well. And the separation between domain logic and domain "infrastructure" (id generation, etc ) can be  clean or not.  

I see two case for domain sharing : 
- either the domain is shared among the same organisation. this case pledge for a same persistence mechanism. Usually organisation keep one mechanism per application. But if inside one organization multiple persistence co-exist, then aggregate design must be mostly interface based and logic mostly resides inside domain service. Domain Service can be injected inside Infrastructured Domain Aggregate for instance.
- either the domain is shared above the organisation. This case is very difficult to handle I think. At Most Value Object can be shared easily. Rules regarding aggregates id, relationships etc, all this is somehow unique to the organisation or suborganization. Because by essence a domain is something that has the less reason to be shared out of one organization. The same rule apply for the multu persistence organization I thinK

I think the jpa subproject was a good compromise, but perhaps I can not remember well without the code.

**Comment by adrienlauer** [comment]
I agree that domains are meant to be shared inside a defined organization. Reuse across organization is difficult at best and may be not desirable. We will definitely keep the abstract base classes that are not tied to JPA (the "blank" one as @ejemba said) because they are the core of the business framework and the foundation for everything else. And we need to continue to support and promote the use of JPA annotations.

But as we want to move to more behavior-rich entities and value objects (to avoid the [anemic domain model](http://martinfowler.com/bliki/AnemicDomainModel.html) issue), the JPA base classes should go. I think we are on the right way, because they provided very little added value and the whole architecture is cleaner without them (domain and persistence implementation are completely orthogonal, as they should be). 

In rare cases (such as a particularly invasive persistence implementation), we cannot have a behavior-rich model AND persistence independence. As @ejemba noted, interface-based entities with the behavior moved to domain services is still a solution in those cases.

**Comment by pith** [comment]
Fixed 75d8c2ce791729827f0ef3a3990908057d9c8085.
